### PR TITLE
Search icon added

### PR DESCRIPTION
**Pull request by nishtha53**
image
Search icon added

### CODE REVIEW

**Comment by Halim-Shams** [comment]
Hey @nishtha53 tnx for contributing, It'll be beautiful to make some changes, like: make the search icon little smaller and also make sure there is some space between placeholder and the icon.

**Comment by nishtha53** [comment]
@Halim-Shams sure

**Comment by nishtha53** [comment]
image

@Halim-Shams  is this looking good to you?

**Comment by Halim-Shams** [comment]
@nishtha53 yes, it's better now. I'll merge it, tnx for contributing!

**Comment by nishtha53** [comment]
@Halim-Shams please add hacktoberfest-accepted label to it.

**Comment by Halim-Shams** [comment]
@nishtha53 I added hacktoberfest-accepted, staring the repo would be a favor. tnx ☺🙏

**Pull request merged**
